### ISSUE TITLE
Allow global .env files

### ISSUE THREAD

**Issue by mtongnz** [dcflachs/compose_plugin#23]
I'd like to allow global .env files.  This lets me put all my settings in one file and use it accross multiple docker_compose files.

I've implemented the basics of this and will add a PR soon.  Annoyingly, I had also integrated with the UI to allow this but an update wiped it out.  I might re-do it but as I use code server to manage my compose files, I'm not too worried about it.

**Comment by dcflachs** [comment]
Any reason this is preferred over specifying the env file path in the [compose file](https://docs.docker.com/compose/compose-file/05-services/#env_file)?

**Comment by mtongnz** [comment]
I have a couple of reasons for this approach...

1. env_file doesn't let you use env variables in the compose file, only in the container.  For example, if using Traefik, it's easier to have a global DOMAIN variable and use that in the labels for each container to set Traefik

2. Each container needs the env_file set and gets all the env variables.  I only want the containers to get what they need so I define each env variable in the compose file, but have them reference my global env vars.

Here's an excert from my tools compose file which shows how I do it:
```
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    # ports:
    #   - 8443:8443
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      UMASK: ${UMASK}
      TZ: ${TZ}
      HASHED_PASSWORD: ${CODE_SERVER_HASHED_PASSWORD}
      DEFAULT_WORKSPACE: ${CODE_SERVER_DEFAULT_WORKSPACE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPDATA}code-server:/config
      - ${APPDATA}:/appdata
      - ${WWW}:/www
      - ${UNRAID_PLUGINS_DIR}:/UnraidPlugins
      - ${DOCKER_COMPOSE_DIR}:/DockerCompose
      - ${DOCUMENTS}:/Documents
    labels:
      traefik.http.routers.code.rule: Host(`code.${DOMAIN}`)
      traefik.http.routers.code.entryPoints: https
      traefik.http.routers.code.tls: true
      traefik.http.services.code.loadbalancer.server.port: 8443
      traefik.enable: true
      
      folder.view: Tools
      net.unraid.docker.icon: ${APPDATA}icons/traefik.png
      net.unraid.docker.webui: https://traefik.${DOMAIN}
      net.unraid.docker.managed: 'composeman'
    networks:
      - traefik_proxy
```

If there's a better way to do this, I'd love to know.  I couldn't find a better way.
